### ISSUE TITLE
Should we move the models to markdown?

### ISSUE THREAD

**Issue by abhilashlr** [ember-learn/upgrade-guide#12]
We have a good start with moving all the in-file constants to separate model files that host the JSON structure.

**Problem statement:**
As we add more of this in the file, it might look huge and difficult to maintain.

**Possible solutions:**
1. We can use showdown or broccoli-static-site-json to compile markdown content to json and use them as ember data models which will eliminate the need for bundling all the json as part of the upgrade guide - helps reduce the asset size. 
2. In future if we have ember's deprecations available as API returning JSON, we can use the same ember models to connect to that APIs and use it in the UI.

Thoughts @kennethlarsen @JennyJudova?

## Models to migrate to markdown:
- [x] Ember JS Features & Deprecations
- [x] Ember CLI Features & Deprecations
- [x] Ember data Features & Deprecations
- [ ] Versions (As a separate PR)?

**Comment by JennyJudova** [comment]
I definitely think this is the right way to go, and both solutions look sound.

**Comment by abhilashlr** [comment]
I can pick this up @JennyJudova @kennethlarsen if we agree to start initial works on markdown first. Progressively we can figure out APIs in future. Thoughts?

**Comment by kennethlarsen** [comment]
Sounds good to me @abhilashlr

**Comment by abhilashlr** [comment]
> Sounds good to me @abhilashlr

Awesome, I can pick this up next then.

**Comment by abhilashlr** [comment]
@kennethlarsen @JennyJudova As a first step moved deprecations model into markdown. I'll iterate on top of this quickly.
