### ISSUE TITLE
Basic linters for project

### ISSUE THREAD

**Issue by abhilashlr** [ember-learn/upgrade-guide#13]
Since we are just setting up this repo, should we think of linters for all the files that we might have? There are a basic set of linters already in place, it would be nice if we can have rules like standard prettier or airbnb styles in place.

Ember-cli follows: 
https://github.com/ember-cli/ember-cli/blob/master/.eslintrc.js

**Comment by JennyJudova** [comment]
Completely support this! And I think it makes sense to use the same linter as ember-cli.

**Comment by abhilashlr** [comment]
@kennethlarsen Should we default to prettier style for linting? Here's what I had in mind:
1. ESLint: prettier with single quotes, semicolons, etc, like below:
    ```
    {
      singleQuote: true,
      semi: true,
      bracketSpacing: true,
      endOfLine: 'lf',
      tabs: false,
      tabWidth: 2
    }
    ```
2. Stylelint: `stylelint-config-standard`
3. Template lint: defaults to octane

**Comment by rwjblue** [comment]
I’d vote for doing the setup I describe in emberjs/rfcs#628 😃

**Comment by kennethlarsen** [comment]
Agree with Robert! @abhilashlr is that something you can help out with?

**Comment by abhilashlr** [comment]
@rwjblue yep, precisely what I meant as well citing few example configurations. I think as mentioned in the RFC, we can restrict to `singleQuote: true`.

**Comment by abhilashlr** [comment]
@kennethlarsen Sure, I will work on it 👍

**Comment by abhilashlr** [comment]
@kennethlarsen @rwjblue Here you go https://github.com/ember-learn/upgrade-guide/pull/22. Let me know if there are some changes that need to be done in the setting up of the rules.
@rwjblue Can you please clarify on the order of the `extends` array property in `.eslintrc.js` file as well or does the order not matter?
