### ISSUE TITLE
Write blueprints for the data being added.

### ISSUE THREAD

**Issue by abhilashlr** [ember-learn/upgrade-guide#15]
The blueprint should create the respective md files in the right folders.

@kennethlarsen do you have a good suggestion for the blueprint name and the parameters?

**Comment by abhilashlr** [comment]
`ember g upgrade-model 3.18 —ember-js`

Or something similar ? How does this look?

**Comment by JennyJudova** [comment]
@abhilashlr do you mind if we pair on this? I've never created a blueprint so would love to learn.

**Comment by abhilashlr** [comment]
Sure @JennyJudova :) What is the blueprint name we should be building - thoughts? @kennethlarsen ?

**Comment by kennethlarsen** [comment]
@abhilashlr @JennyJudova feel free to pair on how it should look. It should match the current data structure we have.

**Comment by abhilashlr** [comment]
Hi @JennyJudova could you please DM me on Discord to work on this? discord handle: abhilashlr#1553
