### ISSUE TITLE
Format ember-cli-update command as code

### ISSUE THREAD

**Issue by kennethlarsen** [ember-learn/upgrade-guide#18]
See if we have something in https://ember-styleguide.netlify.app/ to support it. If not then wrap in `<pre></pre>`

**Comment by abhilashlr** [comment]
The ESCodeSample that we currently use in this app has been removed in 4.0.1 version of styleguide. Considering that we would be migrating to that version soon, as part of PR #21, the same has been moved to `<pre></pre>` tags. Once that is merged, I believe we can close this issue @kennethlarsen ?
