### ISSUE TITLE
Fix Versions array of integers to strings

### ISSUE THREAD

**Issue by abhilashlr** [ember-learn/upgrade-guide#23]
1.1 and 1.10 don’t have a difference and only 1.10 would be taken for consideration for the dropdown. Instead implement them as array of strings so that versions like 1.1 and 1.10 are distinguishable.

**Comment by JennyJudova** [comment]
I think that can be done by changing 1.1 to 1.01 ? What do you think?

**Comment by abhilashlr** [comment]
Our ember ecosystem releases use version formatting like `2.1`, and `2.10` so I'm not sure if marking it as `2.01` might relate easily when someone searches for it in the upgrade guide.

**Comment by rwjblue** [comment]
The idea here is that these are SemVer major + minor values. Storing them as numbers (what we do now) is just invalid, we absolutely should migrate to using strings.

**Comment by JennyJudova** [comment]
@abhilashlr @rwjblue That makes sense. I can make the change. Might change the pre-release versions to have 'PR' in the name (as per the documentation) while Iam at it.
