### ISSUE TITLE
Support query params

### ISSUE THREAD

**Issue by kennethlarsen** [ember-learn/upgrade-guide#3]
So it's possible to send upgrade paths as a URL e.g. `/upgrade?fromVersion=3.16&toVersion=3.17`

https://github.com/offirgolan/ember-parachute

**Comment by abhilashlr** [comment]
Do we need to handle this as part of `/upgrade` route or the existing `/index` route @kennethlarsen

**Comment by kennethlarsen** [comment]
I was thinking `index`. FYI: @JennyJudova has already started work on query params

**Comment by abhilashlr** [comment]
Anything that I can pick up? @kennethlarsen

**Comment by kennethlarsen** [comment]
@abhilashlr This would be cool https://github.com/ember-learn/upgrade-guide/issues/6

**Comment by kennethlarsen** [comment]
Fixed in https://github.com/ember-learn/upgrade-guide/pull/9
