### ISSUE TITLE
assign id to versions 

### ISSUE THREAD

**Issue by JennyJudova** [ember-learn/upgrade-guide#30]
As Ember js, Cli and Data versions are strings rather than numbers there are sometimes issues which versions are displayed between the to and from versions. 

For example '3.8' is read as 3.80 not 3.08. 

Assigning an id to a version will give them a numerical value by which they can be arranged.

**Comment by abhilashlr** [comment]
I can pick this up @JennyJudova @kennethlarsen

**Comment by JennyJudova** [comment]
@abhilashlr go for it 👍

**Comment by abhilashlr** [comment]
@kennethlarsen @JennyJudova there you go, a PR to solve comparisons.
