### ISSUE TITLE
Componentize the Ember Versions form (Part 2 of 2)

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/upgrade-guide#45]
## Problem

Once #44 has been completed and merged, we can invoke the `<EmberVersionsForm>` component in the `index` route.

### Part 2: Simplify `index` route

- [ ] In the controller, remove the actions `doNotSubmitForm`, `updateFromVersion`, and `updateToVersion`.

- [ ] In the controller, create an action called `displayChanges`. The function receives `fromVersion` and `toVersion` as a hash. For now (this behavior will change in another issue), the function updates the tracked properties `this.fromVersion` and `this.toVersion`:

    ```javascript
    // app/controllers/index.js

    versions = VERSIONS;
    @tracked fromVersion = '3.15';
    @tracked toVersion = VERSIONS[VERSIONS.length - 1];

    @action displayChanges({ fromVersion, toVersion }) { ... }
    ```

- [ ] In the route template, replace the `<form>` element with `<EmberVersionForm>` component. Pass `displayChanges` to the component via `@onSubmit`.

- [ ] Check that everything works by running the app locally. All tests should continue to pass.

**Comment by ijlee2** [comment]
General notes: Hi, everyone. To allow more people to participate in Hacktoberfest, please claim only 1 issue in this repo (unless there are no others who can help). 🙂

Please check `#hacktoberfest` on [Discord](https://discord.gg/emberjs) to find other repos that can use your help. Thanks and happy Hacktoberfest!

**Comment by jpsanantonio** [comment]
I'd love to work on this. Please assign this to me. Thanks!

**Comment by ijlee2** [comment]
@jpsanantonio Can you give me a few minutes? Need to first merge a pull request that will affect your issue.

**Comment by jpsanantonio** [comment]
No worries, take your time. I'll start after I'm done with my tasks at work (probably around 5pm PST). :)

**Comment by ijlee2** [comment]
I think you will want to work with the latest code in your forked repo. I believe you can run:

```bash
# Set upstream
git remote set upstream git@github.com:ember-learn/upgrade-guide.git

# Check that setting upstream worked (you will see 2 lines for origin, and another 2 lines for upstream)
git remote -v

# Get the latest code and branches
git checkout master
git fetch upstream
git merge upstream/master
git push origin master
```

If you type `git log`, you should see the [latest commit message in this repo](https://github.com/ember-learn/upgrade-guide/commits/master). At the time of writing, the latest commit message is `Move Ember versions file (#53)`.

Let me know if you run into issues with these commands:

**Comment by ijlee2** [comment]
Completed in #54
