### ISSUE TITLE
Separate form and search results (Part 2 of 2)

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/upgrade-guide#49]
## Problem

Please wait till #48 has been completed and merged.

### Part 2: Update `index` route

- [ ] Add a submit button to the `<EmberVersionsForm>` component, with the label `Find Changes` and the test selector `data-test-button="Find Changes"`. Update the backing class so that changing a select option no longer calls the `submitForm` action. Update tests accordingly.

- [ ] Update `displayChanges` in the `index` controller to make a route transition. We should now to be able to click on `Find Changes` button to transition from `index` to `changes`.

- [ ] Delete the `index` route file and test file.

- [ ] Write application tests to describe what a user can do in the `index` route. Please write tests to check the following:

    - `tests/acceptance/index-test.js`
        - When we visit the index route, we see the form for selecting Ember versions ✅
        - When we select Ember versions, the URL does not change
        - When we submit the form, we are redirected to the changes route
        - When we submit the form, we see the features and deprecations that occurred ✅
        - When we submit the form with fromVersion greater than toVersion, we see 0 features and 0 deprecations

    Note, `✅ `means the test has been written already and can be skipped from this step.

## References

- [Application tests for in whats-new-in-emberland](https://github.com/ember-learn/whats-new-in-emberland/blob/master/tests/acceptance/index-test.js)

**Comment by ijlee2** [comment]
General notes: Hi, everyone. To allow more people to participate in Hacktoberfest, please claim only 1 issue in this repo (unless there are no others who can help). 🙂

Please check `#hacktoberfest` on [Discord](https://discord.gg/emberjs) to find other repos that can use your help. Thanks and happy Hacktoberfest!

**Comment by takshch** [comment]
Sir, Please assign this issue to me. I can work on this issue. Thank you

**Comment by ijlee2** [comment]
@takshch Thank you for helping out with the Upgrade Guide! If you have questions, feel free to reach out by commenting in this issue, or in the `#hacktoberfest` channel at Ember Discord.

**Comment by takshch** [comment]
@ijlee2  changes route was not getting queryParams. So I have to pass { queryParams:..} as 2nd argument in transitionToRoute.
Is there is any good way to achieve the same goal of queryParams?

```js
this.transitionToRoute('changes', {
  queryParams: {
        fromVersion,
        toVersion
      }
});
````

**Comment by ijlee2** [comment]
@takshch If I'm understanding the issue that you encountered correctly, the `index` controller should be first updated to remove query parameters. The code is a leftover from #48.

```javascript
// Before

export default class IndexController extends Controller {
  queryParams = ['fromVersion', 'toVersion'];

  versions = VERSIONS;
  @tracked fromVersion = '3.15';
  @tracked toVersion = VERSIONS[VERSIONS.length - 1];

  @action displayChanges({ fromVersion, toVersion }) {
    this.fromVersion = fromVersion;
    this.toVersion = toVersion;
  }
}
```

```javascript
// After

export default class IndexController extends Controller {
  @action displayChanges({ fromVersion, toVersion }) {
    // TODO: Transition route
  }
}
```

Note, there's an [RFC to deprecate the controller's transition methods](https://github.com/emberjs/rfcs/pulls). You will want to use the `router`'s service methods instead:

```javascript
export default class IndexController extends Controller {
  @service router;

  @action displayChanges({ fromVersion, toVersion }) {
    this.router.transitionTo(...);
  }
}
```

**Comment by takshch** [comment]
Why acceptance test for 'When we submit the form with fromVersion equals to toVersion, we see 0 features and 0 deprecations'?
I have created pull request please review and merge it #61 
Thanks

**Comment by takshch** [comment]
Linting errors are fixed.
