### ISSUE TITLE
Remove non-stable versions from <EmberVersionsForm> component

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/upgrade-guide#57]
## Background

In #53, we found that selecting any one of these versions in the `<EmberVersionsForm>` component will result in an error:

```
1.0 Prerelease
1.0 Prerelease 2
1.0 RC1
1.0 RC2
1.0 RC3
1.0 RC4
1.0 RC5
1.0 RC6
1.0 RC7
1.0 RC8
1.0.0 Beta 2
1.0.0 Beta 9
1.0.0 Beta 12
1.0.0 Beta 14
1.0.0 Beta 15
1.0.0 Beta 16
1.0.0 Beta 18
1.0.0 Beta 19
1.2 Beta 2
2.0 Beta
2.4-LTS
```

## Problem

I'm guessing that the error occurs due to the [`compare` method](https://github.com/ember-learn/upgrade-guide/blob/f830a334600f1ee20e24c90c8000d6b007262a41/app/components/list-features-deprecations.js#L17-L18). I don't think we're passing strings that the method can understand (e.g. `'1.0 Prerelease 2'`).

## TODOs

I think we can take one of two options:

- [ ] First, see if we can update the strings in `app/utils/ember-versions.js` to match the Markdown file names found in `source` directory.

    I think the Markdown file names _are_ strings that `compare` can understand. ([see tests for `compare`](https://github.com/omichelsen/compare-versions/blob/master/test/compare.js))

- [ ] If the step above didn't work, delete the problematic versions from `app/utils/ember-versions.js`. In short, we'll list only the stable versions on the website.

**Comment by Jogius** [comment]
I'd like to work on this problem, and your fix seems to be working. However, I'm not sure which Markdown files belong to 
```
1.2 Beta 2
2.4-LTS
```
since there is no Markdown file for version `1.2` at all and the `2.4.md` files probably belong to the `2.4` entry in [app/utils/ember-versions.js](https://github.com/ember-learn/upgrade-guide/blob/master/app/utils/ember-versions.js).

If you can tell me what to do with those entries, I'd be glad to be assigned this issue!

**Comment by ijlee2** [comment]
Hi, @Jogius. Thanks for your interest in helping out with the Upgrade Guide. I've assigned the issue to you.

To my understanding (I haven't checked this yet), if a Markdown file doesn't exist, the user won't see an error. When you updated those 2 versions to `1.2-beta.2` and `2.4-lts`, did selecting these versions result in no error?

**Comment by Jogius** [comment]
Hey @ijlee2, I tested around a bit and changing it to `1.2-beta.2` and `2.4-lts` doesn't prevent the errors! As long as there's no Mardown file for the given string (so in this case `1.2-beta.2` and `2.4-lts`), there will be errors in the console. 

Should I remove those two entries from the list or create new Markdown files (I'd need to know the format/information in that case).

**Comment by ijlee2** [comment]
@Jogius Thanks for verifying! Let's remove the 2 entries from the list. I can create another issue if we did need to keep the two around.

**Comment by Jogius** [comment]
@ijlee2 I created a pull request that should fix the issue, would you kindly take a look at it as soon as the tests finished?

**Comment by ijlee2** [comment]
@Jogius Yep, I will review now.
