### ISSUE TITLE
Add dynamic upgrade instructions

### ISSUE THREAD

**Issue by kennethlarsen** [ember-learn/upgrade-guide#6]
Based on the versions selected we should display the ember-cli update command https://github.com/ember-cli/ember-cli-update

**Comment by abhilashlr** [comment]
I will pick this up, please assign to me 👍

**Comment by abhilashlr** [comment]
@kennethlarsen There you go, PR on the ember-cli-update commands.

**Comment by kennethlarsen** [comment]
Fixed in https://github.com/ember-learn/upgrade-guide/pull/8
