### ISSUE TITLE
Add a link inviting contributors to help with content

### ISSUE THREAD

**Issue by jenweber** [ember-learn/upgrade-guide#81]
Right now, if someone goes to https://upgrade.emberjs.com they will not know how to update the data, if they want to help contribute.

To do:
- Add a link to the repo and an invitation to help out at the bottom of the page

**Comment by fozy81** [comment]
Happy to take a look at this

**Comment by fozy81** [comment]
Added link https://github.com/ember-learn/upgrade-guide/pull/87, please review thanks! @jenweber

**Comment by locks** [comment]
Related PR has been merged!
