### ISSUE TITLE
It is possible to pick an older version as the "To" version

### ISSUE THREAD

**Issue by locks** [ember-learn/upgrade-guide#91]
At the moment is it possible to pick an older version as the "to" and a newer version as the "from", breaking everything.
I see two possible approaches to fixing this:
1. Somehow limit the "to" version you can pick based on the "from" version picked. This would make an impossible state impossible.
2. Make it so that it doesn't matter the order of the versions picked, only the range. To me this is the better solution, as just letting the user pick the version range feels more permissive and blocking or limiting picks. This might imply some small UI tweaks to remove "from" and "to" wording, or even rework how the user can select the range at all.

## Tasks
- [ ] Disable "Find Changes" button if version range is invalid
- [ ] Remove invalid version from "to" selector after "from" version is picked

**Comment by MehulKChaudhari** [comment]
Hey @locks, Can I take this issue?

**Comment by locks** [comment]
Assigned 👍
