### ISSUE TITLE
Terminal instructions blend into text

### ISSUE THREAD

**Issue by locks** [ember-learn/upgrade-guide#92]
At the moment the upgrade guide includes instructions on how to run `ember-cli-update` in the terminal to upgrade your application. However, since these code blocks don't have any styling to them and they are in a page with a lot of text, they blend in too much and are easy to miss.

A styling similar to what we have in the [Guides](https://guides.emberjs.com/release/getting-started/quick-start/#toc_install-ember) should be introduced.

**Comment by arafatiqbal** [comment]
I like this idea, if it's fine I'm going to take this on, should be straight forward.
